#pragma once

#include "initguid.h"
#include "stdafx.h"

#include "Registrar.h"
#include "ComBase.h"

// {B4FE8B13-40D0-438A-B4C2-DE4522951071}
_declspec(selectany) GUID CLSID_FFBDriver = 
	{ 0xB4FE8B13, 0x40D0, 0x438A, { 0xB4, 0xC2, 0xDE, 0x45, 0x22, 0x95, 0x10, 0x71 } };

//IID_IDirectInputEffectDriver

class FFBDriver
	: public CComBase<>, public InterfaceImpl<IDirectInputEffectDriver>
{
public:
	FFBDriver();
	~FFBDriver();

	STDMETHODIMP FFBDriver::QueryInterface(REFIID riid, LPVOID *ppv);

	HRESULT STDMETHODCALLTYPE DeviceID(DWORD, DWORD, DWORD, DWORD, LPVOID);
	HRESULT STDMETHODCALLTYPE GetVersions(LPDIDRIVERVERSIONS);
	HRESULT STDMETHODCALLTYPE Escape(DWORD, DWORD, LPDIEFFESCAPE);
	HRESULT STDMETHODCALLTYPE SetGain(DWORD, DWORD);
	HRESULT STDMETHODCALLTYPE SendForceFeedbackCommand(DWORD, DWORD);
	HRESULT STDMETHODCALLTYPE GetForceFeedbackState(DWORD, LPDIDEVICESTATE);
	HRESULT STDMETHODCALLTYPE DownloadEffect(DWORD, DWORD, LPDWORD, LPCDIEFFECT, DWORD);
	HRESULT STDMETHODCALLTYPE DestroyEffect(DWORD, DWORD);
	HRESULT STDMETHODCALLTYPE StartEffect(DWORD, DWORD, DWORD, DWORD);
	HRESULT STDMETHODCALLTYPE StopEffect(DWORD, DWORD);
	HRESULT STDMETHODCALLTYPE GetEffectStatus(DWORD, DWORD, LPDWORD);
};

